name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  analyze:
    needs: build
    uses: ./.github/workflows/build.yml
